//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.01 at 10:13:04 PM CDT 
//


package nfl.season.scorestrip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="g" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="eid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="gsis" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="q" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hnn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hs" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="vnn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="vs" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="rz" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ga" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="gt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="gd" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gms"
})
@XmlRootElement(name = "ss")
public class Ss {

    @XmlElement(required = true)
    protected Ss.Gms gms;

    /**
     * Gets the value of the gms property.
     * 
     * @return
     *     possible object is
     *     {@link Ss.Gms }
     *     
     */
    public Ss.Gms getGms() {
        return gms;
    }

    /**
     * Sets the value of the gms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ss.Gms }
     *     
     */
    public void setGms(Ss.Gms value) {
        this.gms = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="g" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="eid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="gsis" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="q" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="hnn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="hs" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="vnn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="vs" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="rz" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ga" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="gt" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="gd" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="w" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "g"
    })
    public static class Gms {

        protected List<Ss.Gms.G> g;
        @XmlAttribute(name = "gd")
        protected Byte gd;
        @XmlAttribute(name = "w")
        protected Byte w;
        @XmlAttribute(name = "y")
        protected Short y;
        @XmlAttribute(name = "t")
        protected String t;

        /**
         * Gets the value of the g property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the g property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ss.Gms.G }
         * 
         * 
         */
        public List<Ss.Gms.G> getG() {
            if (g == null) {
                g = new ArrayList<Ss.Gms.G>();
            }
            return this.g;
        }

        /**
         * Gets the value of the gd property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getGd() {
            return gd;
        }

        /**
         * Sets the value of the gd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setGd(Byte value) {
            this.gd = value;
        }

        /**
         * Gets the value of the w property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getW() {
            return w;
        }

        /**
         * Sets the value of the w property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setW(Byte value) {
            this.w = value;
        }

        /**
         * Gets the value of the y property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setY(Short value) {
            this.y = value;
        }

        /**
         * Gets the value of the t property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getT() {
            return t;
        }

        /**
         * Sets the value of the t property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setT(String value) {
            this.t = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="eid" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="gsis" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="t" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="q" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="h" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hnn" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hs" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="vnn" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="vs" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rz" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ga" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="gt" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class G {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "eid")
            protected Integer eid;
            @XmlAttribute(name = "gsis")
            protected Integer gsis;
            @XmlAttribute(name = "d")
            protected String d;
            @XmlAttribute(name = "t")
            protected String t;
            @XmlAttribute(name = "q")
            protected String q;
            @XmlAttribute(name = "k")
            protected String k;
            @XmlAttribute(name = "h")
            protected String h;
            @XmlAttribute(name = "hnn")
            protected String hnn;
            @XmlAttribute(name = "hs")
            protected Byte hs;
            @XmlAttribute(name = "v")
            protected String v;
            @XmlAttribute(name = "vnn")
            protected String vnn;
            @XmlAttribute(name = "vs")
            protected Byte vs;
            @XmlAttribute(name = "p")
            protected String p;
            @XmlAttribute(name = "rz")
            protected String rz;
            @XmlAttribute(name = "ga")
            protected String ga;
            @XmlAttribute(name = "gt")
            protected String gt;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the eid property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getEid() {
                return eid;
            }

            /**
             * Sets the value of the eid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setEid(Integer value) {
                this.eid = value;
            }

            /**
             * Gets the value of the gsis property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getGsis() {
                return gsis;
            }

            /**
             * Sets the value of the gsis property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setGsis(Integer value) {
                this.gsis = value;
            }

            /**
             * Gets the value of the d property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getD() {
                return d;
            }

            /**
             * Sets the value of the d property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setD(String value) {
                this.d = value;
            }

            /**
             * Gets the value of the t property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getT() {
                return t;
            }

            /**
             * Sets the value of the t property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setT(String value) {
                this.t = value;
            }

            /**
             * Gets the value of the q property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQ() {
                return q;
            }

            /**
             * Sets the value of the q property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQ(String value) {
                this.q = value;
            }

            /**
             * Gets the value of the k property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getK() {
                return k;
            }

            /**
             * Sets the value of the k property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setK(String value) {
                this.k = value;
            }

            /**
             * Gets the value of the h property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getH() {
                return h;
            }

            /**
             * Sets the value of the h property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setH(String value) {
                this.h = value;
            }

            /**
             * Gets the value of the hnn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHnn() {
                return hnn;
            }

            /**
             * Sets the value of the hnn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHnn(String value) {
                this.hnn = value;
            }

            /**
             * Gets the value of the hs property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getHs() {
                return hs;
            }

            /**
             * Sets the value of the hs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setHs(Byte value) {
                this.hs = value;
            }

            /**
             * Gets the value of the v property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getV() {
                return v;
            }

            /**
             * Sets the value of the v property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setV(String value) {
                this.v = value;
            }

            /**
             * Gets the value of the vnn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVnn() {
                return vnn;
            }

            /**
             * Sets the value of the vnn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVnn(String value) {
                this.vnn = value;
            }

            /**
             * Gets the value of the vs property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getVs() {
                return vs;
            }

            /**
             * Sets the value of the vs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setVs(Byte value) {
                this.vs = value;
            }

            /**
             * Gets the value of the p property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP() {
                return p;
            }

            /**
             * Sets the value of the p property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP(String value) {
                this.p = value;
            }

            /**
             * Gets the value of the rz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRz() {
                return rz;
            }

            /**
             * Sets the value of the rz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRz(String value) {
                this.rz = value;
            }

            /**
             * Gets the value of the ga property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGa() {
                return ga;
            }

            /**
             * Sets the value of the ga property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGa(String value) {
                this.ga = value;
            }

            /**
             * Gets the value of the gt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGt() {
                return gt;
            }

            /**
             * Sets the value of the gt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGt(String value) {
                this.gt = value;
            }

        }

    }

}
